#!/usr/bin/python3

import re
import time
import argparse
import os
import sys
import pprint
import paho.mqtt.client as mqtt
import re

sys.path.append('/home/tell/proj/python')

from perlish import *

parser =  argparse.ArgumentParser(description="do multiple mqtt publish operations");
parser.add_argument("--verbose", default=False, action='store_true');
parser.add_argument('pub', metavar='PUB', type=str, nargs='*', default=0,
			   help="list of topic=message items to publish");

args = parser.parse_args();

printf("pubs=[%d]%s\n", len(args.pub), str(args.pub));

def on_connect(client, userdata, flags, rc):
    print("Connected with result code "+str(rc))

mq = mqtt.Client()
mq.connect("ariel", 1883, 30)

for p in args.pub:
    [topic,msg] = re.split('=', p);
    printf("%s <- %s\n", topic, msg);
    mq.publish(topic, msg);
    

while(mq.want_write()):
    mq.loop_write()

